services:
  - type: web
    name: sleep-health-dashboard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn SleepHealth_Analysis_Main:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0